config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # get 'show', to: "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :interests, only:[:create]
    resources :reviews, only:[:create]
  end

  resources :plans, except:[:destroy] do
    resources :event_plans, only:[:create]
  end

  resources :reviews, only:[:destroy]
  resources :interests, only:[:destroy]

  get 'events/tagged', to: "events#tagged", as: :tagged
  get "my_page", to: "users#my_page"
end

app/views/shared/_eventcards.html.erb
<div class="row mt-3">
  <% @events.each do |event|%>
    <div class="col-xl-3 col-lg-4 col-md-4 col-md-6 col-sm-12">
      <div class="card-trip-home">
        <%= cl_image_tag(event.photo, width: 500, height: 400, crop: :fill) %>
        <div class="card-trip-infos">
          <div class="">
            <h4 class="tab-text-content mx-2"><%= link_to event.name, event_path(event), { :class=>"stretched-link" }  %></h4>
          </div>
          <!--           <#= link_to (cl_image_tag event.user.photo, class:"card-trip-user-big avatar-bordered"), event_path(event) %> -->
        </div>
        <div class="mx-3">
          <p>Best View:  <%= event.date %></p>
          <% event.tag_list.each do |tag| %>
            <%= link_to '#'+tag, events_path(tag: tag), class: "tab-text-tag mx-1 px-1" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_interested_events.html.erb
<div class="row mt-3">
  <% if current_user.interests.present? %>
    <% current_user.interests.each do |interest|%>
      <div class="col-xl-3 col-lg-4 col-md-4 col-md-6 col-sm-12">
        <div class="card-trip-home">
          <%= cl_image_tag(interest.event.photo, width: 500, height: 400, crop: :fill) %>
          <div class="card-trip-infos">
            <div class="">
              <h4 class="tab-text-content mx-2"><%= link_to interest.event.name, event_path(interest.event), { :class=>"stretched-link" }  %></h4>
            </div>
          </div>
          <div class="mx-3">
            <p>Best View:  <%= interest.event.date %></p>
            <!--             <#% event.tag_list.each do |tag| %>
              <%#= link_to '#'+tag, events_path(tag: tag), class: "tab-text-tag mx-1 px-1" %>
            <%# end %> -->
            <%= link_to interest_path(interest), method: :delete, data: { confirm: "Do you really want to delete the event?" } do %>
              <div class = "btn btn-mypage m-2">Delete</div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="d-flex justify-content-center">
      <p class="btn btn-secondery mx-auto my-3"><%= link_to "Find Events", events_path %></p>
    </div>
  <% end %>
</div>

app/views/shared/_my_events.html.erb
<div class="row mt-3">
  <% current_user.events.each do |event|%>
    <div class="col-xl-3 col-lg-4 col-md-4 col-md-6 col-sm-12">
      <div class="card-trip-home">
        <%= cl_image_tag(event.photo, width: 500, height: 400, crop: :fill) %>
        <div class="card-trip-infos">
          <div class="">
            <h4 class="tab-text-content mx-2"><%= link_to event.name, event_path(event), { :class=>"stretched-link" }  %></h4>
          </div>
        </div>
        <div class="mx-3">
          <p>Best View:  <%= event.date %></p>
          <!--           <%# event.tag_list.each do |tag| %>
            <%#= link_to '#'+tag, events_path(tag: tag), class: "tab-text-tag mx-1 px-1" %>
          <%# end %> -->
          <%= link_to event_path(event), method: :delete, data: { confirm: "Do you really want to delete the event?" } do %>
            <div class = "btn btn-mypage m-2">Delete</div>
          <% end %>
          <%#= render 'events/edit_form' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <div class="d-flex align-self-end">
      <div><%= image_tag "traveltomo-logo.png" %></div>
      <h2 class="mx-3 logo-text">Traveltomo</h2>
    </div>
  <% end %>
  <!-- button for responsive (start)-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- button for responsive (finish)-->
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="d-flex align-items-center">
      <!-- search button start -->
      <div class="input-group-prepend d-flex align-items-center position-search">
        <i class="fas fa-search navbar-search"></i>
        <%= simple_form_for :search, url: events_path, method: "GET" do |f| %>
          <%= f.input :query, label: false, input_html: {class: 'form-control d-flex align-items-center fa', value: (params[:search][:query] if params[:search])}, placeholder: "find an event" %>
          <!-- <button type="submit"></i></button> -->
        <% end %>
      </div>
      <!-- search button end -->
      <!-- my order start -->
      <div><%= link_to "My Page", my_page_path, class: "nav-link navbar-text" %></div>
      <!-- my order end -->
      <!-- my plan start -->
      <!--       <div class="">
        <%# if user_signed_in? && current_user.plans.present? %>
          <div><%#= link_to "My Plan", plans_path, class: "nav-link navbar-text" %></div>
        <%# end %>
      </div> -->
      <!-- my plan end -->
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag 'traveltomo-logo.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <p class="m-3 ml-1">Hi, <%= current_user.first_name %></p>
              <%= link_to "Setting", edit_user_registration_path(current_user), class: "dropdown-item navbar-text" %>
              <%= link_to "Create an Event", new_plan_path, class: "dropdown-item navbar-text" %>
              <%#= link_to "My Page", my_page_path, class: "dropdown-item navbar-text" %>
              <%= link_to "Create a Plan", new_plan_path, class: "dropdown-item navbar-text" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item navbar-text" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link navbar-text" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>