config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'
  # get 'show', to: "pages#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :events do
    resources :interests, only:[:create]
    resources :reviews, only:[:create]
  end

  resources :plans, except:[:destroy] do
    resources :event_plans, only:[:create]
  end

  resources :reviews, only:[:destroy]
  resources :interests, only:[:destroy]

  get 'events/tagged', to: "events#tagged", as: :tagged
  get "my_page", to: "users#my_page"
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :reviews, dependent: :destroy
  has_many :pictures, dependent: :destroy
  has_many :interests_users, :through => :interests, :source => :user

  belongs_to :user

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [ :name, :location, :date, :genre],
  associated_against: {
    tags: [ :name ]
  },
  using: {
    tsearch: { prefix: true }
  }
  validates :name, presence: true, uniqueness: true
  validates :date, presence: true
  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  
  mount_uploader :photo, PhotoUploader
  mount_uploader :gallery1, PhotoUploader
  mount_uploader :gallery2, PhotoUploader
  mount_uploader :gallery3, PhotoUploader

  acts_as_taggable_on :tags
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:search]
      query = params[:search][:query]
      @tags = params[:search][:tags].reject(&:blank?) if params[:search][:tags].present?

      if query.present? && @tags != nil
        @events = policy_scope(Event).global_search(query).tagged_with(@tags)
        # @plans = policy_scope(Plan).global_search(query).tagged_with(@tags)
      elsif query.present?
        @events = policy_scope(Event).global_search(query)
        # @plans = policy_scope(Plan).global_search(query)
      elsif @tags.any?
        @events = policy_scope(Event).tagged_with(@tags)
        # @plans = policy_scope(Plan).tagged_with(@tags)
      end
    elsif params[:tag].present?
      @events = policy_scope(Event).tagged_with(params[:tag])
      # @plans = policy_scope(Plan).tagged_with(params[:tag])
    else
      @events = policy_scope(Event)
      # @plans = policy_scope(Plan)
    end
  end

  def tagged
    if params[:tag].present?
      @events = policy_scope(Event).tagged_with(params[:tag])
    else
      @events = policy_scope(Event)
    end
  end

  def show
    @event = policy_scope(Event).find(params[:id])
    authorize @event
    @review = Review.new
    @event = Event.find(params[:id])
    @interest = Interest.find_by(user: current_user, event: @event) if user_signed_in?
    @events = Event.where.not(latitude: nil, longitude: nil)
    @markers = [{
                  lat: @event.latitude,
                  lng: @event.longitude,
                  infoWindow: { content: render_to_string(partial: "/events/info_window", locals: { event: @event }) }
    }]
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    authorize @event
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    authorize @event
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    authorize @event
    @event.destroy
    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :date, :photo, :tag_list)
  end

  def create_pictures
    images = params.dig(:event, :pictures) || []
    images.each do |image|
      @event.pictures.create(image: image)
    end
  end
end

app/views/events/_add_eventplan.html.erb
<button type="button" class="btn" data-toggle="modal" data-target="#add_event_form" data-whatever="@getbootstrap">
  <h2 class="add-meal"><i class="fas fa-plus-circle"></i></h2>
</button>
<div class="modal fade" id="add_event_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Add an event</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for ([@plan, EventPlan.new]) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="form-inputs">
            <%= f.association :event, collection: Event.where.not(id: @plan.events), required: true %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondery" data-dismiss="modal">Close</button>
            <%= f.button :submit, "Add Event", class: "btn btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_edit_form.html.erb
<button type="button" class="d-flex align-items-end banner-btn" data-toggle="modal" data-target="#event_form" data-whatever="@getbootstrap">
  <i class="fas fa-edit btn btn-secondery"></i>
</button>
<div class="modal fade" id="event_form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="exampleModalLabel">Edit your event</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@event) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <div class="form-inputs">
            <%= f.input :name, placeholder: @event.name %>
            <%= f.input :description, placeholder: @event.description%>
            <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder:"Choose dates", label:false %>
            <%= f.input :location %>
            <%= f.input :tag_list %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
            <%= simple_fields_for :pictures do |picture| %>
              <%= picture.input :image, as: :file, input_html: { multiple: true } %>
            <% end %>
          </div>
          <div class="form-actions d-flex justify-content-between">
            <%= f.button :submit, class: "btn btn-main" %>
            <button type="button" class="btn btn-secondery" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container">
  <%= simple_form_for(@event) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :name, placeholder: 'Your event name' %>
      <%= f.input :description, placeholder: 'Something to describe your event' %>
      <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}, placeholder:"Choose dates", label:false %>
      <%= f.input :location %>
      <%= f.input :tag_list %>
      <!--       <div class="container my-3 d-flex justify-content-between">
        <div
          id="map"
          style="width: 1110px;
          height: 250px;"
          data-markers="<%= @markers.to_json %>"
        ></div> -->
    </div>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :pictures, as: :file, input_html: { multiple: true } %>
  </div>
  <div class="form-actions d-flex justify-content-between">
    <%= f.button :submit, class: "btn btn-main" %>
    <%= link_to 'Back', root_path, class: "btn btn-secondery"%>
  </div>
<% end %>
</div>

app/views/events/_info_window.html.erb
<h6><%= link_to @event.name, event_path(event) %></h6>

app/views/events/index.html.erb
<div class="container">
  <div class="d-flex my-4">
    <h3><i class="fas fa-map-marked-alt"></i></h3>
    <h2 class="mx-3">Find Your Destination</h2>
  </div>
  <!-- search bar & filter start-->
  <div class="row mb-5">
    <div class="col">
      <%= simple_form_for :search, url: events_path, method: "GET" do |f| %>
        <%= f.input :query, label: false, input_html: {class: 'form-control', value: (params[:search][:query] if params[:search])}, placeholder: "Find an event" %>
        <%  ActsAsTaggableOn::Tag.most_used(7).map do |tag|%>
          <% if @tags.nil? %>
            <%= check_box_tag 'search[tags][]', tag.name, false %>
          <% else %>
            <%= check_box_tag 'search[tags][]', tag.name, (params[:search] ? params[:search][:tags].include?(tag.name) : false) %>
          <% end %>
          <%= tag.name %> &nbsp;&nbsp;
        <% end %>
        <div class="my-3">
          <%= f.submit "Search", class: "btn btn-main" %>
          <%= link_to "Reset", events_path, class: "btn btn-secondery" %>
        </div>
      <% end %>
    </div>
    <!-- search bar & filter end-->
    <div class="container">
      <ul class="nav nav-tabs" id="myTab" role="tablist" style="
  font-size: large;
  font-weight: bold;">
        <li class="nav-item">
          <a class="tab-text nav-link active" id="event-tab" data-toggle="tab" href="#event" role="tab" aria-controls="event" aria-selected="true">Events</a>
        </li>
        <li class="nav-item">
          <a class="tab-text nav-link" id="area-tab" data-toggle="tab" href="#area" role="tab" aria-controls="area" aria-selected="false">By Area</a>
        </li>
      </ul>
      <!-- CONTENT -->
      <div class="tab-content" id="myTabContent">
        <!-- content nav -->
        <div class="tab-panel show active" id="event" role="tabpanel" aria-labelledby="event-tab">
          <%= render 'shared/eventcards' %>
        </div>
        <!--  <div class="tab-panel" id="plan" role="tabpanel" aria-labelledby="plan-tab">
          <div class="row mt-3">
            <%#= render 'shared/plancard_index' %>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
    </div>
    <div class="container">
      <h1>Create a New Event</h1>
      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<!-- banner start -->
<div class="banner mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @event.photo %>');">
  <div class="d-flex align-items-end justify-content-center" style="height: 60vh;">
    <h2 class="white banner-name"><%= @event.name %></h2>
    <% if current_user == @event.user %>
      <%= render 'edit_form' %>
    <% end %>
    <p class="banner-p text-break">Best view: <%= @event.date %></p>
    <!-- interest -->
    <div class="int-btn">
      <% if user_signed_in? && current_user.interested_events.include?(@event) %>
        <%= link_to interest_path(@interest), method: :delete, data: { confirm: "You have removed this event from your interest list" } do %>
          <div class = "btn btn-main m-2">Remove Interest</div>
        <% end %>
      <% else %>
        <%= link_to event_interests_path(@event), method: :post, data: { confirm: "You have add this event in your interest list" } do %>
          <div class = "btn btn-main m-2">Interested</div>
        <% end %>
      <% end %>
    </div>
    <!-- interest end -->
  </div>
</div>
<!-- banner end -->
<!-- content start -->
<div class="event-bcard pb-4 justify-content-around ml-4 mr-4">
  <div class="event-card px-3">
    <!-- <div class="col-12 col-sm-12 col-md-6 px-3">-->
    <p>Description: <%= @event.description %></p>
    <p>Access: <%= @event.access %></p>
  </div>
  <div id="carouselExampleIndicators" class="carousel slide float-right" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= cl_image_tag (@event.gallery1), class: "d-block w-100" %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag (@event.gallery2), class: "d-block w-100" %>
      </div>
      <div class="carousel-item">
        <%= cl_image_tag (@event.gallery3), class: "d-block w-100" %>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<!-- event-card -->
<div class="container">
  <div class="row no-gutters mt-4">
    <div class="col-12 col-sm-12 col-md-6 px-2">
      <div class="container">
        <h2>Address</h2>
        <i class="fa fa-map-marker-alt"></i> <%= @event.location %>
      </div>
      <div class="container my-3 d-flex justify-content-between">
        <div
  id="map"
  style="width: 100%;
  height: 300px;"
  data-markers="<%= @markers.to_json %>"
></div>
      </div>
    </div>
    <div class="col-12 col-sm-12 col-md-6">
      <div class="container">
        <h2>Review</h2>
        <%= render 'reviews/form' %>
        <% if @event.reviews.present? %>
          <!-- this is for showing review -->
          <p class="review-comment mt-4">Review comment</p>
          <div class="scroll p-3">
            <% @event.reviews.each do |review| %>
              <div class="d-flex align-self-start mb-2">
                <% if review.user.photo.present? %>
                  <%= cl_image_tag review.user.photo, class: "avatar" %>
                <% else %>
                  <%= image_tag "traveltomo-logo.png", class: "avatar" %>
                <% end %>
                <div>
                  <h6 class="mx-2"><%= review.user.first_name %> <%= review.user.last_name %></h6>
                  <p class="m-2"><%= review.content %></p>
                  <p class="m-2">
                    <% review.rating.to_i.times do  %>
                      <i class="fas fa-star bento-star"></i>
                    <% end %>
                    <% (5 - review.rating).to_i.times do  %>
                      <i class="fas fa-star bento-star-gray"></i>
                    <% end %>
                  </p>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <br>
          <p>Be the first one to review!!</p>
        <% end %>
      </div>
    </div>
    <div class="container text-center">
      <%= link_to "All Events", events_path, class: "btn btn-secondery" %>
    </div>
  </div>
</div>